apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pi
        image: ubuntu:22.04
        command: ["/bin/bash"]
        args: ["-c", "sleep", "300"]
      restartPolicy: Never
  backoffLimit: 4
