apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl", "sleep(300)"]
      restartPolicy: Never
  backoffLimit: 4
